### PR TITLE
Issue #112 - Updated the Kubernetes version of the GKE templates

### PR DESCRIPTION
**Pull request by glovecchi0**
GKE version (Regular) 1.28.8-gke.1095000
Rancher version v2.8.4

### CODE REVIEW

**Review by ajithijk — APPROVED** [review]
Tested and worked fine

**Review by dnoland1 — COMMENTED** [review]
Would it make sense to also change the comment at https://github.com/rancher/tf-rancher-up/blob/main/recipes/upstream/google-cloud/gke/terraform.tfvars.example#L24 ?

**Comment by dnoland1** [comment]
And the drone check is failing - https://drone-pr.rancher.io/rancher/tf-rancher-up/190/1/4 likely because https://github.com/rancher/tf-rancher-up/blob/main/modules/distribution/gke/docs.md?plain=1#L31 was not updated

**Comment by dnoland1** [comment]
and when I tried to run the terraform, I got this error:
```
helm_release.ingress-nginx: Creating...
╷
│ Error: Unable to continue with install: could not get information about the resource ServiceAccount "ingress-nginx" in namespace "ingress-nginx": serviceaccounts "ingress-nginx" is forbidden: User "client" cannot get resource "serviceaccounts" in API group "" in the namespace "ingress-nginx"
│
│   with helm_release.ingress-nginx,
│   on main.tf line 23, in resource "helm_release" "ingress-nginx":
│   23: resource "helm_release" "ingress-nginx" {
```

**Comment by glovecchi0** [comment]
> And the drone check is failing - https://drone-pr.rancher.io/rancher/tf-rancher-up/190/1/4 likely because https://github.com/rancher/tf-rancher-up/blob/main/modules/distribution/gke/docs.md?plain=1#L31 was not updated

Modified docs.tf and terraform.tfvars.example as suggested.

**Pull request closed without merging**
