### PR TITLE
Feature/GitHub actions

### PR DESCRIPTION
**Pull request by glovecchi0**
Converted CI pipeline from Drone to GitHub Action

### CODE REVIEW

**Review by dnoland1 — CHANGES_REQUESTED** [review]
It doesn't appear the GH action was run and don't see it listed at https://github.com/rancher/tf-rancher-up/actions . Perhaps GH actions need to be enabled for the repository.

I would also revert the GKE version change from this PR.

**Comment by glovecchi0** [comment]
> It doesn't appear the GH action was run and don't see it listed at https://github.com/rancher/tf-rancher-up/actions . Perhaps GH actions need to be enabled for the repository.
> 
> I would also revert the GKE version change from this PR.

Reverted GKE version change.

**Comment by dnoland1** [comment]
@leodotcloud Can you check if GitHub actions have been enabled for this repository?

**Comment by leodotcloud** [comment]
I have merged this PR. I don't think the pipelines get triggered from forks. Need to create a branch directly on the repo and create a PR.

**Comment by leodotcloud** [comment]
I have created a PR here: https://github.com/rancher/tf-rancher-up/pull/133. Please feel free to contribute directly to that branch.

**Pull request merged**
